apiVersion: v1
kind: Pod
metadata:
  labels:
    run: medium-po
  name: medium-po
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - medium

  containers:
  - image: nginx
    name: medium-po

