apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: frontend-rs
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - image: nginx
        name: manoj