apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes: # Define a shared volume
  - name: itk-emptydir
    emptyDir: {}

  containers:
  - name: busybox-1
    image: busybox:latest
    command: ["sleep", "3600"]
    volumeMounts: # Mount the shared volume
      - name: itk-emptydir
        mountPath: /shared-data  


  - name: busybox-2
    image: busybox:latest
    command: ["sleep", "3600"]
    volumeMounts: # Mount the shared volume
      - name: itk-emptydir
        mountPath: /shared-data  

